# Generated by Django 5.1.14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0077_alter_participantevent_event_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='googlemeetbotlogin',
            name='sso_mode',
            field=models.CharField(choices=[('saml', 'SAML'), ('oidc', 'OIDC')], default='saml', max_length=10),
        ),
    ]
